- backend/src/MarketPlace.sol
- backend/test/Marketplace.t.sol
- backend/test/Wastewise.t.sol
1. made some corrections on the marketplace contract
2. wrote the test for the marketplace
> Marketplace test completed-

- backend/src/MarketPlace.sol
- backend/src/RwasteWise.sol
- backend/src/Wastewise.sol
1. I added new functionalities to the `WasteWise.sol` contract and update documentation
2. I updated documentation of the `RwasteWise.sol` contract
3. I updated documentation of the `MarketPlace.sol` contract
> Feature/smart contract update/mars

- backend/src/MarketPlace.sol
- backend/src/RwasteWise.sol
I changed the solidity version to a stable one
> changed solidity version

- backend/src/MarketPlace.sol
- backend/src/Wastewise.sol
- backend/test/Marketplace.t.sol
- backend/test/Wastewise.t.sol
Fixed some bugs in the test script
> Fixed test bugs

- backend/src/Wastewise.sol
> modified allAdmins

- frontend/constants/index.tsx
- frontend/constants/marketPlaceABI.json
- frontend/constants/wasteWiseABI.json
- frontend/src/App.tsx
- frontend/src/components/CardFour.tsx
- frontend/src/components/CardOne.tsx
- frontend/src/components/CardThree.tsx
- frontend/src/components/CardTwo.tsx
- frontend/src/components/Sidebar.tsx
- frontend/src/components/TableOne.tsx
- frontend/src/components/dashboard/home/Home.tsx
- frontend/src/context/index.tsx
- frontend/src/index.css
- frontend/src/main.tsx
- frontend/src/pages/Dashboard/Wallet.tsx
- frontend/src/pages/Landing.tsx
- frontend/src/pages/Register.tsx
- frontend/tailwind.config.js
- frontend/yarn.lock
> Frontend changes

- frontend/constants/index.tsx
- frontend/constants/tokenABI.json
- frontend/src/components/CardOne.tsx
- frontend/src/components/CardTwo.tsx
1. Frontend changes or updates
> Frontend changes or updates

- backend/src/MarketPlace.sol
- backend/src/Wastewise.sol
- frontend/constants/wasteWiseABI.json
> Update wastewise contract

- backend/src/Wastewise.sol
> edited addAdmins

- backend/src/MarketPlace.sol
- backend/src/Wastewise.sol
1. Update marketplace contract
> Update marketplace contract

- backend/src/MarketPlace.sol
- backend/src/Wastewise.sol
- backend/test/Marketplace.t.sol
- backend/test/Wastewise.t.sol
- frontend/src/pages/Dashboard/CreateEvent.tsx
- frontend/src/pages/Dashboard/Deposit.tsx
- frontend/src/pages/Dashboard/SingleEvent.tsx
- frontend/src/utils/index.ts
> Major code refactoring

- frontend/src/components/CardOne.tsx
- frontend/src/components/Sidebar.tsx
- frontend/src/pages/Dashboard/CreateAdmin.tsx
- frontend/src/pages/Dashboard/SingleEvent.tsx
- frontend/src/pages/Dashboard/Wallet.tsx
- frontend/src/pages/Register.tsx
1. Worked on types errors for deployment to vercel
> Worked on types errors for deployment to vercel

- frontend/src/pages/Landing.tsx
1. Fix blockquote color that overshadows the text colors
> Fix blockquote color that overshadows the text colors

- frontend/src/App.tsx
> Update demo page

- frontend/src/pages/Dashboard/CreateAdmin.tsx
> Update wastewise address

- frontend/src/components/WasteWise.tsx
- frontend/src/pages/Dashboard/SingleEvent.tsx
> Update frontend for demo

- frontend/src/pages/Dashboard/Wallet.tsx
> Update wallet page

- frontend/src/pages/Landing.tsx
> Update roadmap content

- README.md
> new deployments

- backend/src/Wastewise.sol
- backend/test/Wastewise.t.sol
> Update contract tests

- frontend/src/pages/Register.tsx
> Added register user event

- frontend/src/components/Button.tsx
> Update button component

- frontend/src/components/DashboardNav.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/context/index.tsx
- frontend/src/pages/Dashboard/Wallet.tsx
- frontend/src/pages/Register.tsx
- frontend/src/wagmi.ts
> Implement wallet events

- frontend/src/pages/Dashboard/Wallet.tsx
1. Fix type issue wallet events
> Fix type issue wallet events

- frontend/src/pages/Dashboard/Wallet.tsx
> Update wallet events

- frontend/src/pages/Register.tsx
1. Make registration page signup button responsive
> Make registration page signup button responsive

- frontend/src/components/CardFour.tsx
- frontend/src/components/CardOne.tsx
- frontend/src/components/CardThree.tsx
- frontend/src/components/CardTwo.tsx
- frontend/src/components/ChartOne.tsx
- frontend/src/components/ChartTwo.tsx
- frontend/src/components/TableOne.tsx
- frontend/src/hooks/useBalance.tsx
- frontend/src/pages/Dashboard/CreateAdmin.tsx
- frontend/src/pages/Dashboard/Deposit.tsx
1. Update frontend demo update
> Update frontend demo update

- frontend/src/pages/Dashboard/SingleEvent.tsx
- frontend/src/pages/Dashboard/Wallet.tsx
> Refactor for prod

- frontend/src/App.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/components/Sidebar.tsx
- frontend/src/components/TableOne.tsx
- frontend/src/components/dashboard/home/Stats.tsx
- frontend/src/pages/Dashboard/CreateAdmin.tsx
- frontend/src/pages/Dashboard/Wallet.tsx
> Major Updates for prod

- frontend/src/components/TableOne.tsx
- frontend/src/components/dashboard/home/Stats.tsx
> Minor Updates for prod

- frontend/src/components/dashboard/home/Stats.tsx
> Minor Updates for prod 2

- frontend/src/components/NotificationCard.tsx
- frontend/src/components/dashboard/home/Home.tsx
- frontend/src/pages/Landing.tsx
> Update FAQ section

- frontend/src/components/Sidebar.tsx
> Update sidebar active
